# Generated by OmopViewer 0.2.0
# Be careful editing this file

library(bslib)
library(CohortCharacteristics)
library(DiagrammeR)
library(dplyr)
library(DT)
library(ggplot2)
library(glue)
library(gt)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(purrr)
library(readr)
library(rlang)
library(shiny)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))

panels <- c("summarise_cohort_count", "summarise_cohort_attrition")
