# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {
  # cohort and codelist ----
  # codelist_name details
  output$codelist_name_details <- DT::renderDT({
    DT::datatable(codelistDefinitions[[input$codelist_name]], rownames = FALSE, escape = FALSE)
  })
  output$codelist_presence <- shiny::renderUI({
    formatCriteria <- function(x) {
      if (length(x) == 0) return(character())
      stringr::str_glue("`{x}`") |>
        glue::glue_collapse(sep = ", ", last = " and ")
    }
    result <- cohortDefinitions |>
      dplyr::filter(.data$codelist_name %in% input$codelist_name) |>
      dplyr::select("cohort_name", "definition") |>
      dplyr::group_by(.data$cohort_name) |>
      dplyr::group_split() |>
      purrr::map_chr(\(x) {
        nm <- unique(x$cohort_name)
        val <- stringr::str_replace_all(x$definition, "_", " ")
        id <- stringr::str_starts(val, "inclusion")
        if (sum(id) > 0) {
          inclusion <- substr(val[id], 11, nchar(val[id])) |>
            formatCriteria()
          inclusion <- paste0("inclusion criteria ", inclusion)
        } else {
          inclusion <- character()
        }
        res <- c(formatCriteria(val[!id]), inclusion) |>
          glue::glue_collapse(sep = ", ", last = " and ")
        paste0("* **", nm, "** for ", res, ".")
      })
    c("This codelist is used in the following cohorts:", result) |>
      paste0(collapse = "\n\n") |>
      shiny::markdown()
  })
  # definition
  output$cohort_definition <- shiny::renderUI({
    x <- cohortDefinitions |>
      dplyr::filter(.data$cohort_name == input$cohort_name) |>
      dplyr::select("cohort_name", "definition", "value")
    start <- x$value[x$definition == "cohort_start_date"]
    end <- x$value[x$definition == "cohort_end_date"]
    result <- c(
      paste0("**Cohort start date:** ", start),
      paste0("**Cohort end date:** ", end)
    )
    inclusion <- x |>
      dplyr::filter(stringr::str_starts(.data$definition, "inclusion"))
    inclusionText <- purrr::map_chr(seq_len(nrow(inclusion)), \(k) {
      paste0(k, ". ", inclusion$value[inclusion$definition == paste0("inclusion ", k)])
    })
    if (length(inclusionText) > 0) {
      inclusionText <- c("**Inclusion criteria:**", inclusionText)
    }
    shiny::markdown(paste0(c(result, inclusionText), collapse = "\n\n"))
  })
  
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  
  # summarise_omop_snapshot -----
  createSummariseOmopSnapshot <- shiny::reactive({
    data |>
      filterData("summarise_omop_snapshot", input) |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_gt <- gt::render_gt({
    createSummariseOmopSnapshot()
  })
  output$summarise_omop_snapshot_gt_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_download_type),
    content = function(file) {
      obj <- createSummariseOmopSnapshot()
      gt::gtsave(data = obj, filename = file)
    }
  )

  # common pickers ----
  keepPickers(panels = panels, pickers = pickers, input = input, session = session)
  # summarise_cohort_count -----
  ## tidy summarise_cohort_count -----
  getTidyDataSummariseCohortCount <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input) 
    if (nrow(result) > 0) {
      result <- result |>
        omopgenerics::tidy() |>
        dplyr::select(!c("variable_level", "table_name")) |>
        tidyr::pivot_wider(names_from = "variable_name", values_from = "count")
    } else {
      result <- dplyr::tibble(
        cdm_name = character(),
        cohort_name = character()
      )
      for (var in input$summarise_cohort_count_variable_name) {
        result <- result |>
          dplyr::mutate(!!var := integer())
      }
    }
    result
  })
  output$summarise_cohort_count_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortCount(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_count.csv",
    content = function(file) {
      getTidyDataSummariseCohortCount() |>
        readr::write_csv(file = file)
    }
  )
  ## table summarise_cohort_count -----
  createOutput9 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::tableCohortCount(
      result,
      header = input$summarise_cohort_count_gt_header,
      groupColumn = input$summarise_cohort_count_gt_groupColumn,
      hide = c(input$summarise_cohort_count_gt_hide, "variable_level", "table_name")
    )
  })
  output$summarise_cohort_count_gt <- gt::render_gt({
    createOutput9()
  })
  output$summarise_cohort_count_gt_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_count.", input$summarise_cohort_count_gt_download_type),
    content = function(file) {
      obj <- createOutput9()
      gt::gtsave(data = obj, filename = file)
    }
  )
  ## plot summarise_cohort_count -----
  createOutput10 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::plotCohortCount(
      result,
      facet = input$summarise_cohort_count_ggplot2_10_facet,
      colour = input$summarise_cohort_count_ggplot2_10_colour
    )
  })
  output$summarise_cohort_count_ggplot2_10 <- shiny::renderPlot({
    createOutput10()
  })
  output$summarise_cohort_count_ggplot2_10_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_count.", "png"),
    content = function(file) {
      obj <- createOutput10()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_count_ggplot2_10_download_width),
        height = as.numeric(input$summarise_cohort_count_ggplot2_10_download_height),
        units = input$summarise_cohort_count_ggplot2_10_download_units,
        dpi = as.numeric(input$summarise_cohort_count_ggplot2_10_download_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## tidy summarise_cohort_attrition -----
  getTidyDataSummariseCohortAttrition <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_attrition", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_attrition.csv",
    content = function(file) {
      getTidyDataSummariseCohortAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## table summarise_cohort_attrition -----
  createOutput3 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::tableCohortAttrition(
      result,
      header = input$summarise_cohort_attrition_gt_3_header,
      groupColumn = input$summarise_cohort_attrition_gt_3_groupColumn,
      hide = c(input$summarise_cohort_attrition_gt_3_hide, "variable_level")
    )
  })
  output$summarise_cohort_attrition_gt_3 <- gt::render_gt({
    createOutput3()
  })
  output$summarise_cohort_attrition_gt_3_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_attrition.", input$summarise_cohort_attrition_gt_3_download_type),
    content = function(file) {
      obj <- createOutput3()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## diagram summarise_cohort_attrition -----
  createOutput4 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::plotCohortAttrition(
      result
    )
  })
  output$summarise_cohort_attrition_grViz_4 <- DiagrammeR::renderGrViz({
    createOutput4()
  })
  output$summarise_cohort_attrition_grViz_4_download <- shiny::downloadHandler(
    filename = paste0("output_grViz_summarise_cohort_attrition.", "png"),
    content = function(file) {
      obj <- createOutput4()
      DiagrammeR::export_graph(
        graph = obj,
        file_name = file,
        fily_type = "png",
        width = as.numeric(input$summarise_cohort_attrition_grViz_4_download_width),
        height = as.numeric(input$summarise_cohort_attrition_grViz_4_download_height)
      )
    }
  )


  # summarise_cohort_overlap -----
  ## tidy summarise_cohort_overlap -----
  getTidyDataSummariseCohortOverlap <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_overlap", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_overlap_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_overlap_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_overlap_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortOverlap(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_overlap_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_overlap.csv",
    content = function(file) {
      getTidyDataSummariseCohortOverlap() |>
        readr::write_csv(file = file)
    }
  )
  ## table summarise_cohort_overlap -----
  createOutput1 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_overlap", input) |>
      cohortNameAddReference()
    CohortCharacteristics::tableCohortOverlap(
      result,
      uniqueCombinations = input$summarise_cohort_overlap_gt_1_uniqueCombinations,
      header = input$summarise_cohort_overlap_gt_1_header,
      groupColumn = input$summarise_cohort_overlap_gt_1_groupColumn,
      hide = input$summarise_cohort_overlap_gt_1_hide
    )
  })
  output$summarise_cohort_overlap_gt_1 <- gt::render_gt({
    createOutput1()
  })
  output$summarise_cohort_overlap_gt_1_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_overlap.", input$summarise_cohort_overlap_gt_1_download_type),
    content = function(file) {
      obj <- createOutput1()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## plot summarise_cohort_overlap -----
  createOutput2 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_overlap", input) |>
      cohortNameAddReference()
    CohortCharacteristics::plotCohortOverlap(
      result,
      facet = input$summarise_cohort_overlap_ggplot2_2_facet,
      uniqueCombinations = input$summarise_cohort_overlap_ggplot2_2_uniqueCombinations
    )
  })
  output$summarise_cohort_overlap_ggplot2_2 <- shiny::renderPlot({
    createOutput2()
  })
  output$summarise_cohort_overlap_ggplot2_2_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_overlap.", "png"),
    content = function(file) {
      obj <- createOutput2()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_width),
        height = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_height),
        units = input$summarise_cohort_overlap_ggplot2_2_download_units,
        dpi = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_dpi)
      )
    }
  )
  # summarise_cohort_timing -----
  ## tidy summarise_cohort_timing -----
  getTidyDataSummariseCohortTiming <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_timing", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_timing_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_timing_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_timing_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortTiming(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_timing_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_timing.csv",
    content = function(file) {
      getTidyDataSummariseCohortTiming() |>
        readr::write_csv(file = file)
    }
  )
  ## table summarise_cohort_timing -----
  createOutput5 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_timing", input) |>
      cohortNameAddReference()
    CohortCharacteristics::tableCohortTiming(
      result,
      uniqueCombinations = input$summarise_cohort_timing_gt_5_uniqueCombinations,
      timeScale = input$summarise_cohort_timing_gt_5_timeScale,
      header = input$summarise_cohort_timing_gt_5_header,
      groupColumn = input$summarise_cohort_timing_gt_5_groupColumn,
      hide = input$summarise_cohort_timing_gt_5_hide
    )
  })
  output$summarise_cohort_timing_gt_5 <- gt::render_gt({
    createOutput5()
  })
  output$summarise_cohort_timing_gt_5_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_timing.", input$summarise_cohort_timing_gt_5_download_type),
    content = function(file) {
      obj <- createOutput5()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## plot summarise_cohort_timing -----
  createOutput6 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_timing", input) |>
      cohortNameAddReference()
    CohortCharacteristics::plotCohortTiming(
      result,
      plotType = input$summarise_cohort_timing_ggplot2_6_plotType,
      timeScale = input$summarise_cohort_timing_ggplot2_6_timeScale,
      facet = input$summarise_cohort_timing_ggplot2_6_facet,
      colour = input$summarise_cohort_timing_ggplot2_6_colour,
      uniqueCombinations = input$summarise_cohort_timing_ggplot2_6_uniqueCombinations
    )
  })
  output$summarise_cohort_timing_ggplot2_6 <- shiny::renderPlot({
    createOutput6()
  })
  output$summarise_cohort_timing_ggplot2_6_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_timing.", "png"),
    content = function(file) {
      obj <- createOutput6()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_width),
        height = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_height),
        units = input$summarise_cohort_timing_ggplot2_6_download_units,
        dpi = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_dpi)
      )
    }
  )


  # summarise_characteristics -----
  ## tidy summarise_characteristics -----
  getTidyDataSummariseCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_characteristics", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## table summarise_characteristics -----
  createOutput7 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_7_header,
      groupColumn = input$summarise_characteristics_gt_7_groupColumn,
      hide = input$summarise_characteristics_gt_7_hide
    )
  })
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      obj <- createOutput7()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## plot summarise_characteristics -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::plotCharacteristics(
      result,
      plotStyle = input$summarise_characteristics_ggplot2_8_plotStyle,
      facet = input$summarise_characteristics_ggplot2_8_facet,
      colour = input$summarise_characteristics_ggplot2_8_colour
    )
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )


  # summarise_large_scale_characteristics -----
  ## tidy summarise_large_scale_characteristics -----
  getTidyDataSummariseLargeScaleCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_large_scale_characteristics", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_large_scale_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_large_scale_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_large_scale_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseLargeScaleCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_large_scale_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_large_scale_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseLargeScaleCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
}
