# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {
  
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  # summarise_omop_snapshot -----
  ## tidy summarise_omop_snapshot -----
  getTidyDataSummariseOmopSnapshot <- shiny::reactive({
    res <- data |>
      filterData("summarise_omop_snapshot", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_omop_snapshot_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_omop_snapshot_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseOmopSnapshot(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_omop_snapshot.csv",
    content = function(file) {
      getTidyDataSummariseOmopSnapshot() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_omop_snapshot -----
  ## output 17 -----
  createOutput17 <- shiny::reactive({
    result <- data |>
      filterData("summarise_omop_snapshot", input)
    OmopSketch::tableOmopSnapshot(
      result
    )
  })
  output$summarise_omop_snapshot_gt_17 <- gt::render_gt({
    createOutput17()
  })
  output$summarise_omop_snapshot_gt_17_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_17_download_type),
    content = function(file) {
      obj <- createOutput17()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_cohort_count -----
  ## tidy summarise_cohort_count -----
  getTidyDataSummariseCohortCount <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_count", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_count_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_count_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_count_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortCount(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_count.csv",
    content = function(file) {
      getTidyDataSummariseCohortCount() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_count -----
  ## output 9 -----
  createOutput9 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::tableCohortCount(
      result,
      header = input$summarise_cohort_count_gt_9_header,
      groupColumn = input$summarise_cohort_count_gt_9_groupColumn,
      hide = input$summarise_cohort_count_gt_9_hide
    )
  })
  output$summarise_cohort_count_gt_9 <- gt::render_gt({
    createOutput9()
  })
  output$summarise_cohort_count_gt_9_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_count.", input$summarise_cohort_count_gt_9_download_type),
    content = function(file) {
      obj <- createOutput9()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 10 -----
  createOutput10 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::plotCohortCount(
      result,
      facet = input$summarise_cohort_count_ggplot2_10_facet,
      colour = input$summarise_cohort_count_ggplot2_10_colour
    )
  })
  output$summarise_cohort_count_ggplot2_10 <- shiny::renderPlot({
    createOutput10()
  })
  output$summarise_cohort_count_ggplot2_10_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_count.", "png"),
    content = function(file) {
      obj <- createOutput10()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_count_ggplot2_10_download_width),
        height = as.numeric(input$summarise_cohort_count_ggplot2_10_download_height),
        units = input$summarise_cohort_count_ggplot2_10_download_units,
        dpi = as.numeric(input$summarise_cohort_count_ggplot2_10_download_dpi)
      )
    }
  )


  # summarise_cohort_attrition -----
  ## tidy summarise_cohort_attrition -----
  getTidyDataSummariseCohortAttrition <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_attrition", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_attrition.csv",
    content = function(file) {
      getTidyDataSummariseCohortAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_attrition -----
  ## output 3 -----
  createOutput3 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::tableCohortAttrition(
      result,
      header = input$summarise_cohort_attrition_gt_3_header,
      groupColumn = input$summarise_cohort_attrition_gt_3_groupColumn,
      hide = input$summarise_cohort_attrition_gt_3_hide
    )
  })
  output$summarise_cohort_attrition_gt_3 <- gt::render_gt({
    createOutput3()
  })
  output$summarise_cohort_attrition_gt_3_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_attrition.", input$summarise_cohort_attrition_gt_3_download_type),
    content = function(file) {
      obj <- createOutput3()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 4 -----
  createOutput4 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::plotCohortAttrition(
      result
    )
  })
  output$summarise_cohort_attrition_grViz_4 <- DiagrammeR::renderGrViz({
    createOutput4()
  })
  output$summarise_cohort_attrition_grViz_4_download <- shiny::downloadHandler(
    filename = paste0("output_grViz_summarise_cohort_attrition.", "png"),
    content = function(file) {
      obj <- createOutput4()
      DiagrammeR::export_graph(
        graph = obj,
        file_name = file,
        fily_type = "png",
        width = as.numeric(input$summarise_cohort_attrition_grViz_4_download_width),
        height = as.numeric(input$summarise_cohort_attrition_grViz_4_download_height)
      )
    }
  )


  # summarise_cohort_overlap -----
  ## tidy summarise_cohort_overlap -----
  getTidyDataSummariseCohortOverlap <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_overlap", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_overlap_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_overlap_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_overlap_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortOverlap(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_overlap_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_overlap.csv",
    content = function(file) {
      getTidyDataSummariseCohortOverlap() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_overlap -----
  ## output 1 -----
  createOutput1 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_overlap", input)
    CohortCharacteristics::tableCohortOverlap(
      result,
      uniqueCombinations = input$summarise_cohort_overlap_gt_1_uniqueCombinations,
      header = input$summarise_cohort_overlap_gt_1_header,
      groupColumn = input$summarise_cohort_overlap_gt_1_groupColumn,
      hide = input$summarise_cohort_overlap_gt_1_hide
    )
  })
  output$summarise_cohort_overlap_gt_1 <- gt::render_gt({
    createOutput1()
  })
  output$summarise_cohort_overlap_gt_1_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_overlap.", input$summarise_cohort_overlap_gt_1_download_type),
    content = function(file) {
      obj <- createOutput1()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 2 -----
  createOutput2 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_overlap", input)
    CohortCharacteristics::plotCohortOverlap(
      result,
      facet = input$summarise_cohort_overlap_ggplot2_2_facet,
      uniqueCombinations = input$summarise_cohort_overlap_ggplot2_2_uniqueCombinations
    )
  })
  output$summarise_cohort_overlap_ggplot2_2 <- shiny::renderPlot({
    createOutput2()
  })
  output$summarise_cohort_overlap_ggplot2_2_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_overlap.", "png"),
    content = function(file) {
      obj <- createOutput2()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_width),
        height = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_height),
        units = input$summarise_cohort_overlap_ggplot2_2_download_units,
        dpi = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_dpi)
      )
    }
  )


  # summarise_cohort_timing -----
  ## tidy summarise_cohort_timing -----
  getTidyDataSummariseCohortTiming <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_timing", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_timing_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_timing_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_timing_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortTiming(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_timing_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_timing.csv",
    content = function(file) {
      getTidyDataSummariseCohortTiming() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_timing -----
  ## output 5 -----
  createOutput5 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_timing", input)
    CohortCharacteristics::tableCohortTiming(
      result,
      uniqueCombinations = input$summarise_cohort_timing_gt_5_uniqueCombinations,
      timeScale = input$summarise_cohort_timing_gt_5_timeScale,
      header = input$summarise_cohort_timing_gt_5_header,
      groupColumn = input$summarise_cohort_timing_gt_5_groupColumn,
      hide = input$summarise_cohort_timing_gt_5_hide
    )
  })
  output$summarise_cohort_timing_gt_5 <- gt::render_gt({
    createOutput5()
  })
  output$summarise_cohort_timing_gt_5_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_timing.", input$summarise_cohort_timing_gt_5_download_type),
    content = function(file) {
      obj <- createOutput5()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 6 -----
  createOutput6 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_timing", input)
    CohortCharacteristics::plotCohortTiming(
      result,
      plotType = input$summarise_cohort_timing_ggplot2_6_plotType,
      timeScale = input$summarise_cohort_timing_ggplot2_6_timeScale,
      facet = input$summarise_cohort_timing_ggplot2_6_facet,
      colour = input$summarise_cohort_timing_ggplot2_6_colour,
      uniqueCombinations = input$summarise_cohort_timing_ggplot2_6_uniqueCombinations
    )
  })
  output$summarise_cohort_timing_ggplot2_6 <- shiny::renderPlot({
    createOutput6()
  })
  output$summarise_cohort_timing_ggplot2_6_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_timing.", "png"),
    content = function(file) {
      obj <- createOutput6()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_width),
        height = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_height),
        units = input$summarise_cohort_timing_ggplot2_6_download_units,
        dpi = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_dpi)
      )
    }
  )


  # summarise_characteristics -----
  ## tidy summarise_characteristics -----
  getTidyDataSummariseCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_characteristics", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_characteristics -----
  ## output 7 -----
  createOutput7 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_7_header,
      groupColumn = input$summarise_characteristics_gt_7_groupColumn,
      hide = input$summarise_characteristics_gt_7_hide
    )
  })
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      obj <- createOutput7()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 8 -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::plotCharacteristics(
      result,
      plotStyle = input$summarise_characteristics_ggplot2_8_plotStyle,
      facet = input$summarise_characteristics_ggplot2_8_facet,
      colour = input$summarise_characteristics_ggplot2_8_colour
    )
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )


  # summarise_large_scale_characteristics -----
  ## tidy summarise_large_scale_characteristics -----
  getTidyDataSummariseLargeScaleCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_large_scale_characteristics", input) |>
      visOmopResults::addSettings() |>
      visOmopResults::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_large_scale_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_large_scale_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_large_scale_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseLargeScaleCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_large_scale_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_large_scale_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseLargeScaleCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_large_scale_characteristics -----
  ## output 0 -----
  createOutput0 <- shiny::reactive({
    result <- data |>
      filterData("summarise_large_scale_characteristics", input)
    simpleTable(
      result,
      header = input$summarise_large_scale_characteristics_gt_0_header,
      group = input$summarise_large_scale_characteristics_gt_0_group,
      hide = input$summarise_large_scale_characteristics_gt_0_hide
    )
  })
  output$summarise_large_scale_characteristics_gt_0 <- gt::render_gt({
    createOutput0()
  })
  output$summarise_large_scale_characteristics_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_large_scale_characteristics.", input$summarise_large_scale_characteristics_gt_0_download_type),
    content = function(file) {
      obj <- createOutput0()
      gt::gtsave(data = obj, filename = file)
    }
  )
}
