# Generated by OmopViewer 0.2.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "logo_title.png",
      width = "auto",
      height = "50px",
      class = "me-3",
      alt = "logo"
    ), 
    ""
  ),
  theme = bslib::bs_theme(preset = "spacelab"),
  # Introduction ----
  bslib::nav_panel(
    title = "Introduction",
    icon = shiny::icon("info"),
    backgroundCard("background.md")
  ),
  # Cohort and codelist details ----
  bslib::nav_menu(
    title = "Cohorts and Codelists",
    icon = shiny::icon("clipboard-list"),
    bslib::nav_panel(
      title = "Codelist details",
      icon = shiny::icon("list"),
      bslib::card(
        bslib::card_title("Codelist details"),
        paste(
          "There are", length(codelistDefinitions), "different codelists used in this study:"
        ),
        shinyWidgets::pickerInput(
          inputId = "codelist_name",
          label = "Codelist name",
          choices = names(codelistDefinitions),
          selected = "insomnia_broad"
        ),
        shiny::uiOutput("codelist_presence"),
        DT::DTOutput("codelist_name_details")
      )
    ),
    bslib::nav_panel(
      title = "Cohort details",
      icon = shiny::icon("user"),
      bslib::card(
        bslib::card_title("Cohort details"),
        paste(
          "There are", length(cohortNames), "different cohorts used in this study:"
        ),
        shinyWidgets::pickerInput(
          inputId = "cohort_name",
          label = "Select cohort",
          choices = cohortNames,
          selected = "insomnia_broad"
        ),
        bslib::card(shiny::uiOutput("cohort_definition"))
      )
    )
  ),
  # Database details ----
  bslib::nav_panel(
    title = "Databases details",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_cdm_name",
          label = "CDM name",
          choices = filterValues$summarise_omop_snapshot_cdm_name,
          selected = filterValues$summarise_omop_snapshot_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        )
      ),
      bslib::nav_panel(
        title = "Snapshot table",
        bslib::card(
          full_screen = TRUE,
          bslib::card_header(
            bslib::popover(
              shiny::icon("download"),
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_gt_download_type",
                label = "File type",
                selected = "docx",
                choices = c("docx", "png", "pdf", "html"),
                multiple = FALSE
              ),
              shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_download", label = "Download")
            ),
            class = "text-end"
          ),
          gt::gt_output("summarise_omop_snapshot_gt")
        )
      )
    )
  ),
  # Results ----
  bslib::nav_menu(
    title = "Results",
    icon = shiny::icon("list"),
    # cohort count ----
    bslib::nav_panel(
      title = "Cohort count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            open = FALSE,
            cdmCohortFilter("summarise_cohort_count"),
            bslib::accordion_panel(
              title = "Variable",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_variable_name",
                label = "Variable name", 
                choices = filterValues$summarise_cohort_count_variable_name,
                selected = filterValues$summarise_cohort_count_variable_name, 
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_cohort_count_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              DT::dataTableOutput("summarise_cohort_count_tidy")
            )
          ),
          bslib::nav_panel(
            title = "Table cohort count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_gt_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_gt_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("variable_name", "estimate_name"),
                      input_id = "summarise_cohort_count_gt_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_count_gt_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_gt_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = NULL,
                      input_id = "summarise_cohort_count_gt_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_gt")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot cohort count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_ggplot2_10_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_facet",
                    label = "facet",
                    selected = "cdm_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_colour",
                    label = "colour",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_cohort_count_ggplot2_10")
              )
            )
          )
        )
      )
    ),
    # cohort attrition ----
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            open = FALSE,
            cdmCohortFilter("summarise_cohort_attrition"),
            bslib::accordion_panel(
              title = "Reason",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_grouping_reason",
                label = "Reason",
                choices = filterValues$summarise_cohort_attrition_grouping_reason,
                selected = filterValues$summarise_cohort_attrition_grouping_reason,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_attrition_grouping_reason_id",
                label = "Reason id",
                choices = filterValues$summarise_cohort_attrition_grouping_reason_id,
                selected = filterValues$summarise_cohort_attrition_grouping_reason_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_cohort_attrition_tidy_columns,
                    selected = filterValues$summarise_cohort_attrition_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_cohort_attrition_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_cohort_attrition_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_gt_3_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_gt_3_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = "reason",
                      input_id = "summarise_cohort_attrition_gt_3_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_gt_3_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_gt_3_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = c("variable_level", "reason_id", "estimate_name"),
                      input_id = "summarise_cohort_attrition_gt_3_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_gt_3")
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_grViz_4_download_width",
                    label = "Width (px)",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_grViz_4_download_height",
                    label = "Height (px)",
                    value = 10
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_grViz_4_download", label = "Download")
                ),
                class = "text-end"
              ),
              DiagrammeR::grVizOutput("summarise_cohort_attrition_grViz_4")
            )
          )
        )
      )
    ),
    # cohort characteristics ----
    bslib::nav_panel(
      title = "Cohort characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shiny::p("NOTE: characterisation was only done for dementia cohort"),
          bslib::accordion(
            cdmCohortFilter("summarise_characteristics", FALSE),
            bslib::accordion_panel(
              title = "Variables and estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_characteristics_variable_name,
                selected = filterValues$summarise_characteristics_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_characteristics_estimate_name,
                selected = filterValues$summarise_characteristics_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_characteristics_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_characteristics_tidy_columns,
                    selected = filterValues$summarise_characteristics_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_characteristics_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_characteristics_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_gt_7_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_gt_7_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("table", "window", "value", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_gt_7_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_gt_7_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = NULL,
                      input_id = "summarise_characteristics_gt_7_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_7_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_gt_7")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_ggplot2_8_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_plotStyle",
                    label = "plotStyle",
                    selected = "barplot",
                    multiple = FALSE,
                    choices = c("boxplot", "barplot", "scatterplot"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_facet",
                    label = "facet",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "table", "window", "value", "variable_name", "variable_level", "estimate_name", "table_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_colour",
                    label = "colour",
                    selected = NULL,
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "table", "window", "value", "variable_name", "variable_level", "estimate_name", "table_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_characteristics_ggplot2_8")
              )
            )
          )
        )
      )
    ),
    # cohort overlap ----
    bslib::nav_panel(
      title = "Cohort overlap",
      icon = shiny::icon("circle-half-stroke"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            cdmCohortFilter("summarise_cohort_overlap"),
            bslib::accordion_panel(
              title = "Overlap",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_overlap_grouping_cohort_name_comparator",
                label = "Cohort name comparator",
                choices = filterValues$summarise_cohort_overlap_grouping_cohort_name_comparator,
                selected = filterValues$summarise_cohort_overlap_grouping_cohort_name_comparator,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_overlap_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_cohort_overlap_variable_name,
                selected = filterValues$summarise_cohort_overlap_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_overlap_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_cohort_overlap_estimate_name,
                selected = filterValues$summarise_cohort_overlap_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_cohort_overlap_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_cohort_overlap_tidy_columns,
                    selected = filterValues$summarise_cohort_overlap_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_cohort_overlap_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_cohort_overlap_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort overlap",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_gt_1_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_overlap_gt_1_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("cohort_name", "cohort_name_comparator", "estimate_name"),
                      input_id = "summarise_cohort_overlap_gt_1_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_overlap_gt_1_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_overlap_gt_1_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = "variable_level",
                      input_id = "summarise_cohort_overlap_gt_1_hide"
                    )
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_cohort_overlap_gt_1_uniqueCombinations",
                    label = "uniqueCombinations",
                    value = c(TRUE)
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_overlap_gt_1")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot cohort overlap",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_overlap_ggplot2_2_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_overlap_ggplot2_2_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_ggplot2_2_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_overlap_ggplot2_2_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_overlap_ggplot2_2_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_overlap_ggplot2_2_facet",
                    label = "facet",
                    selected = c("cdm_name", "cohort_name"),
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "cohort_name_comparator", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_cohort_overlap_ggplot2_2_uniqueCombinations",
                    label = "uniqueCombinations",
                    value = c(TRUE)
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_cohort_overlap_ggplot2_2")
              )
            )
          )
        )
      )
    ),
    # cohort timing ----
    bslib::nav_panel(
      title = "Cohort timing",
      icon = shiny::icon("chart-simple"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_timing_settings_restrict_to_first_entry",
                label = "Restrict to first entry",
                choices = filterValues$summarise_cohort_timing_settings_restrict_to_first_entry,
                selected = filterValues$summarise_cohort_timing_settings_restrict_to_first_entry,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_timing_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_cohort_timing_grouping_cdm_name,
                selected = filterValues$summarise_cohort_timing_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_timing_grouping_cohort_name_reference",
                label = "Cohort name reference",
                choices = filterValues$summarise_cohort_timing_grouping_cohort_name_reference,
                selected = filterValues$summarise_cohort_timing_grouping_cohort_name_reference,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_timing_grouping_cohort_name_comparator",
                label = "Cohort name comparator",
                choices = filterValues$summarise_cohort_timing_grouping_cohort_name_comparator,
                selected = filterValues$summarise_cohort_timing_grouping_cohort_name_comparator,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_timing_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_cohort_timing_variable_name,
                selected = filterValues$summarise_cohort_timing_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_timing_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_cohort_timing_estimate_name,
                selected = filterValues$summarise_cohort_timing_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_cohort_timing_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_cohort_timing_tidy_columns,
                    selected = filterValues$summarise_cohort_timing_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_cohort_timing_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_cohort_timing_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table cohort timing",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_gt_5_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_timing_gt_5_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("cdm_name", "cohort_name_reference", "cohort_name_comparator", "variable_name", "estimate_name"),
                      input_id = "summarise_cohort_timing_gt_5_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = character(),
                      input_id = "summarise_cohort_timing_gt_5_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = NULL,
                      input_id = "summarise_cohort_timing_gt_5_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = "variable_level",
                      input_id = "summarise_cohort_timing_gt_5_hide"
                    )
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_cohort_timing_gt_5_uniqueCombinations",
                    label = "uniqueCombinations",
                    value = c(TRUE)
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_gt_5_timeScale",
                    label = "timeScale",
                    selected = "days",
                    multiple = FALSE,
                    choices = c("days", "years"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_timing_gt_5")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot cohort timing",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_timing_ggplot2_6_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_plotType",
                    label = "plotType",
                    selected = "boxplot",
                    multiple = FALSE,
                    choices = c("boxplot", "density"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_timeScale",
                    label = "timeScale",
                    selected = "days",
                    multiple = FALSE,
                    choices = c("days", "years"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_facet",
                    label = "facet",
                    selected = c("cdm_name", "cohort_name_reference"),
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name_reference", "cohort_name_comparator", "variable_name", "variable_level", "estimate_name", "restrict_to_first_entry"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_colour",
                    label = "colour",
                    selected = "cohort_name_comparator",
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name_reference", "cohort_name_comparator", "variable_name", "variable_level", "estimate_name", "restrict_to_first_entry"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_cohort_timing_ggplot2_6_uniqueCombinations",
                    label = "uniqueCombinations",
                    value = c(TRUE)
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_cohort_timing_ggplot2_6")
              )
            )
          )
        )
      )
    ),
    # large scale characteristics ----
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_analysis",
                label = "Analysis",
                choices = filterValues$summarise_large_scale_characteristics_settings_analysis,
                selected = filterValues$summarise_large_scale_characteristics_settings_analysis,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_large_scale_characteristics_settings_table_name,
                selected = filterValues$summarise_large_scale_characteristics_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_type",
                label = "Type",
                choices = filterValues$summarise_large_scale_characteristics_settings_type,
                selected = filterValues$summarise_large_scale_characteristics_settings_type,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_large_scale_characteristics_grouping_cdm_name,
                selected = filterValues$summarise_large_scale_characteristics_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_large_scale_characteristics_grouping_cohort_name,
                selected = filterValues$summarise_large_scale_characteristics_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_concept_id",
                label = "Concept id",
                choices = filterValues$summarise_large_scale_characteristics_grouping_concept_id,
                selected = filterValues$summarise_large_scale_characteristics_grouping_concept_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_large_scale_characteristics_variable_name,
                selected = filterValues$summarise_large_scale_characteristics_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_large_scale_characteristics_estimate_name,
                selected = filterValues$summarise_large_scale_characteristics_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_large_scale_characteristics_tidy_columns,
                    selected = filterValues$summarise_large_scale_characteristics_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_large_scale_characteristics_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_large_scale_characteristics_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Formatted",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_gt_0_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_gt_0_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("concept_id", "variable_name", "variable_level", "estimate_name", "analysis", "table_name", "type"),
                      input_id = "summarise_large_scale_characteristics_gt_0_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "cdm_name",
                      input_id = "summarise_large_scale_characteristics_gt_0_header"
                    ),
                    sortable::add_rank_list(
                      text = "group",
                      labels = "cohort_name",
                      input_id = "summarise_large_scale_characteristics_gt_0_group"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_large_scale_characteristics_gt_0_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_large_scale_characteristics_gt_0")
              )
            )
          )
        )
      )
    )
  ),
  # nav bar ----
  bslib::nav_spacer(),
  bslib::nav_item(
    shiny::downloadButton(outputId = "download_raw", label = "", icon = shiny::icon("download"))
  ),
  bslib::nav_item(
    bslib::tooltip(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.2.0")
    )
  )
)
